spring:
  application:
    name: "cards-service"
  zipkin:
    base-url: http://localhost:9411/

server:
  port: ${cards-port}
  servlet:
    context-path: ${cards-path}

url:
  mock: http://localhost:8088/mockGetCardsSoap
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
      fetch-registry: true
        
resilience4j:
  retry:
    instances:
      cardsRetry:
        max-attempts: 3
        wait-duration: 1s
    metrics:
      enabled: true
      legacy:
        enabled: true