server:
  port: 9001
  
spring:
  application:
    name: API_GATEWAY
  zipkin:
    base-url: http://localhost:9411/  
    
  cloud:
    gateway:
      routes:
    
      - id: clients-service              
        uri: lb://clients-service        
        predicates:
        - Path=/clients_app/v1/**
     
      - id: products-service               
        uri: lb://products-service         
        predicates:
        - Path=/products_app/v1/**
        
      - id: orders-service               
        uri: lb://orders-service         
        predicates:
        - Path=/orders_app/v1/**
      
      - id: cards-service              
        uri: lb://cards-service         
        predicates:
        - Path=/cards_app/v1/**  
      
      - id: bff-service               
        uri: lb://bff-service         
        predicates:
        - Path=/bff_app/v1/**
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}