version: '2.6'
services:
  mock-server:
      image: mockserver/mockserver:latest
      networks:
        - client-net
      ports:
        - 1080:1080
      environment:
        MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
        MOCKSERVER_PROPERTY_FILE: /config/mock-server/mockserver.properties
        MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mock-server/initializerJson.json
      volumes:
        - type: bind
          source: .
          target: /config
  client-service:
    image: juanmolinagl/undefined-clients:0.0.1-SNAPSHOT
    networks:
        - client-net
    depends_on:
      - mock-server
    ports:
      - 8000:8000
networks:
  client-net:
