openapi: 3.0.1
info:
  title: Trabajo Grupal - Undefined - Clients
  version: v0.0.1
paths:
  /clients_app/v1/clients/{id}:
    get:
      tags:
        - ClientController
      description: Returns a single client
      operationId: getClient
      parameters:
        - name: id
          in: path
          description: ID of client to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ClientDTO'
        '400':
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsDTO'
        '404':
          description: Client not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorsDTO'
components:
  schemas:
    ErrorsDTO:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/ExceptionDTO'
    ExceptionDTO:
      type: object
      properties:
        timestamp:
          type: string
          format: date-time
        code:
          type: integer
          format: int32
        details:
          type: string
    ClientDTO:
      type: object
      properties:
        id:
          type: integer
          format: int64
        dni:
          type: string
        name:
          type: string
        lastName:
          type: string
        address:
          type: string