spring:
  application:
    name: "products-service"
  zipkin:
    base-url: http://localhost:9411/
  data:
    mongodb:
      #uri: mongodb://yourusername:yourpassword@localhost:27017/yourDB
      username: ${mongoUser}
      password: ${mongoPass}
      database: globallogic-proyect
      port: 27017
      host: localhost
      authentication-database: admin
server:
  port: ${products-port}
  servlet:
    context-path: ${products-path}
database:
  url: mongodb://${mongoUser}:${mongoPass}@localhost:27017
resilience4j:
  circuitbreaker:
    instances:
      productsCircuitBreaker:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
