version: "3.8"
services:
  mongodb:
    image: mongo
    restart: always
    container_name: products-mongodb
    networks:
        - products-networks
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: products-mongo-express
    networks:
        - products-networks
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  products-service:
    image: dcusii/undefined-products:1.0.0
    networks:
        - products-networks
    ports:
      - 8100:8100
    depends_on:
      - mongodb
      - mongo-express
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - DATABASE_URL=mongodb://rootuser:rootpass@localhost:27017
volumes:
  data: {}

networks:
  products-networks: