version: "3.8"
services:
  service-discovery:
      image: sporaviral/service-discovery:0.0.1-SNAPSHOT
      ports:
        - "8761:8761"
      networks:
        -  ms-net
        
  config-server:
      image: sofialoria/undefined-configurationserver:0.0.1-SNAPSHOT
      ports:
        - "8943:8943"
      depends_on:
        - service-discovery
      networks:
        - ms-net
      environment:
        EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
        SPRING_DATASOURCE_URL: 'jdbc:h2:file:/tmp/data/configServer'
        
  vault-dev:
      image: vault:latest
      networks:
        - ms-net
      volumes:
        - vault-file:/vault/file
      ports:
        - "8400:8400/tcp"
      environment:
        VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'
        VAULT_DEV_LISTEN_ADDRESS: '0.0.0.0:8400'
      cap_add:
        - IPC_LOCK
      container_name: vault_dev
      entrypoint: "vault server -dev"
      
  insert_secrets:
      image: juanmolinagl/undefined-vault:0.0.1-SNAPSHOT
      networks:
      - ms-net
      ports:
        - "8450:8450"
      restart: on-failure
      depends_on:
        - vault-dev
      environment:
        DATA_URI: 'http://vault-dev:8400'
        
  zipkin-server:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - ms-net
    restart: always #Restart if there is a problem starting up 
    
  api-gateway:
    image: giulianmonti/api_gateway:0.0.1-SNAPSHOT
    ports:
      - "9001:9001"
    networks:
      - ms-net
    depends_on:
      - service-discovery
      - zipkin-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
      
  mock-server:
    image: mockserver/mockserver:latest
    networks:
      - ms-net
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
      MOCKSERVER_PROPERTY_FILE: /config/mock-server/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/mock-server/initializerJson.json
    volumes:
      - type: bind
        source: .
        target: /config
  client-service:
    image: juanmolinagl/undefined-clients:1.0.0
    networks:
        - ms-net
    depends_on:
      - mock-server
      - service-discovery
      - zipkin-server
      - config-server
    ports:
      - 8000:8000
    restart: on-failure
    environment:
      MOCK_URL: 'http://mock-server:1080/api/v1/clients/'
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
      
  mock-soap:
    image: juanmolinagl/mock-soap
    networks:
      - ms-net
    ports:
      - 8088:8088
    environment:
      MOCK_SERVICE_NAME: GetCardsSoap MockService
  cards-service:
    image: sporaviral/undefined-cards:1.0.0
    networks:
      - ms-net
    depends_on:
      - mock-soap
      - service-discovery
      - zipkin-server
      - config-server
    ports:
      - 8300:8300
    restart: on-failure
    environment:
      URL_MOCK: http://mock-soap:8088/mockGetCardsSoap
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
        
  mysqldb:
    container_name: mysqldb
    networks:
      - ms-net
    image: mysql
    volumes:
      - /home/user/Desktop/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: ordersdb
      MYSQL_ROOT_PASSWORD: root
  orders-service:
    image: giulianmonti/orders_app:1.0.0-SNAPSHOT
    networks:
      - ms-net
    depends_on:
      - mysqldb
      - service-discovery
      - zipkin-server
      - config-server
    ports:
      - 8200:8200
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/ordersdb?createDatabaseIfNotExist=true
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
      TZ: America/Argentina/Buenos_Aires

  mongodb:
    image: mongo
    restart: always
    container_name: products-mongodb
    networks:
      - ms-net
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
  mongo-express:
    image: mongo-express
    container_name: products-mongo-express
    networks:
      - ms-net
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: rootuser
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass
      ME_CONFIG_MONGODB_SERVER: mongodb
  products-service:
    image: dcusii/undefined-products:1.0.0
    networks:
      - ms-net
    ports:
      - 8100:8100
    depends_on:
      - mongodb
      - mongo-express
      - service-discovery
      - zipkin-server
      - config-server
    restart: on-failure
    environment:
      SPRING_DATA_MONGODB_HOST: mongodb
      DATABASE_URL: mongodb://rootuser:rootpass@mongodb:27017
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
  
  bff-service:
    image: juanmolinagl/undefined-bff:1.0.0
    networks:
      - ms-net
    restart: on-failure
    ports: 
      - 8500:8500
    depends_on:
      - mysqldb
      - service-discovery
      - zipkin-server
      - config-server
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: '$${EUREKA_URI:http://service-discovery:8761/eureka}'
      SPRING_ZIPKIN_BASEURL: 'http://zipkin-server:9411/'
    
volumes:
     vault-file: {}
     data: {}
     
networks:
  ms-net: