spring:
  application:
    name: "orders-service"
  zipkin:
    base-url: http://localhost:9411/
  datasource:
    url: jdbc:mysql://localhost:3307/ordersdb?createDatabaseIfNotExist=true
    username: ${mysqlUser}
    password: ${mysqlPass}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: ${orders-port}
  servlet:
    context-path: ${orders-path}



resilience4j:
  circuitbreaker:
    instances:
      salesCircuitBreaker:
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED

eureka:
  client:
   serviceUrl:
     defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
